message("${Cyan} CPACK IS SET ${ColourReset}")

set(deb_package_name "print_ip")
set(CPACK_VERBATIM_VARIABLES YES)

set(CPACK_GENERATOR DEB)
set(CPACK_PACKAGE_VERSION_MAJOR "${PROJECT_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${PROJECT_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${PROJECT_VERSION_PATCH}")

set(CPACK_PACKAGE_CONTACT keromvp@gmail.com)

set(CPACK_PACKAGE_FILE_NAME ${deb_package_name})

set(CPACK_PACKAGE_NAME ${deb_package_name})

set(CPACK_PACKAGE_INSTALL_DIRECTORY ${CPACK_PACKAGE_NAME})
set(CPACK_PACKAGE_DIRECTORY "${CMAKE_SOURCE_DIR}/_deb")

set(CPACK_COMPONENTS_GROUPING ALL_COMPONENTS_IN_ONE)#ONE_PER_GROUP)
set(CPACK_DEB_COMPONENT_INSTALL YES)
set(CPACK_SET_DESTDIR true) 
#set(CPACK_INSTALL_PREFIX "/opt/${CMAKE_PROJECT_NAME}")#/${CMAKE_PROJECT_VERSION}") // set install dir
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS YES)
message(STATUS "Components to pack: ${CPACK_COMPONENTS_ALL}")
include(CPack)



