name: build and run tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # install dependencies
    - name: boost
      run: sudo apt-get update && sudo apt-get install -yq libboost-all-dev
    - name: ninja
      run: sudo apt-get install -yq ninja-build
    - name: gcc
      run: sudo apt-get install -yq clang-15
    # build project
    - name: mkdir
      run: mkdir build
    - name: cmake build
      run: cmake --preset linux-x64-release
      shell: bash
      env:
       CC: clang-15
       CXX: clang++-15
    - name: cmake build
      run: cmake --build --preset linux-x64-release
      shell: bash
      env:
       CC: clang-15
       CXX: clang++-15
    # run tests
    - name: run tests
      run: ctest --test-dir ./build/linux-x64-release/test-prj
      shell: bash
      env:
       CC: clang-15
       CXX: clang++-15

