name: build and run tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # install dependencies
    - name: boost
      run: sudo apt-get update && sudo apt-get install -yq libboost-all-dev
    # build project
    - name: mkdir
      run: mkdir build
    - name: cmake build
      run: cmake --preset linux-x64-releasee
    - name: cmake build
      run: cmake --build --preset linux-x64-release
    # run tests
    - name: run tests
      run: ctest --test-dir ./build/linux-x64-release
